/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.handpoint.headstart;

public final class R {
    public static final class array {
        /**  statuses 
         */
        public static int statuses=0x7f060000;
        public static int transaction_statuses=0x7f060002;
        public static int transaction_types=0x7f060001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static int icon=0x7f020000;
        public static int status_connected=0x7f020001;
        public static int status_disconnected=0x7f020002;
    }
    public static final class id {
        public static int alertTitle=0x7f070001;
        public static int button1=0x7f070003;
        public static int button2=0x7f070004;
        public static int button_scan=0x7f070009;
        public static int cancelButton=0x7f07000c;
        public static int icon=0x7f070000;
        public static int message=0x7f070002;
        public static int new_devices=0x7f070008;
        public static int paired_devices=0x7f070006;
        public static int scanning_progress=0x7f07000a;
        public static int scanning_text=0x7f07000b;
        public static int title_new_devices=0x7f070007;
        public static int title_paired_devices=0x7f070005;
    }
    public static final class layout {
        public static int alert_dialog=0x7f030000;
        public static int device_list=0x7f030001;
        public static int device_name=0x7f030002;
        public static int preference_progress_category=0x7f030003;
        public static int progress_dialog=0x7f030004;
        public static int signature_dialog=0x7f030005;
    }
    public static final class raw {
        public static int my=0x7f040000;
    }
    public static final class string {
        public static int app_name=0x7f050000;
        /**  errors 
         */
        public static int bluetooth_not_available=0x7f050028;
        public static int bt_disable_dialog_text=0x7f05001d;
        public static int bt_enable_dialog_text=0x7f05001c;
        /**  Bluetooth dialog 
         */
        public static int bt_enable_dialog_title=0x7f05001b;
        public static int bt_operation_error_text=0x7f050020;
        public static int button_scan=0x7f05000a;
        public static int cancel=0x7f050002;
        /**  common 
         */
        public static int cancelling=0x7f050001;
        public static int close=0x7f050005;
        public static int connect_error_message=0x7f050025;
        public static int connect_ped_message=0x7f050023;
        /**  Connection dialog 
         */
        public static int connect_ped_title=0x7f050022;
        public static int connected=0x7f050031;
        public static int connecting=0x7f050024;
        public static int disconnected=0x7f050032;
        public static int done=0x7f050007;
        /**  Errors 
         */
        public static int error_common=0x7f05003b;
        public static int error_connection_ped=0x7f05002a;
        public static int error_transaction=0x7f05002b;
        public static int ft_checking_status=0x7f050018;
        public static int ft_not_supported=0x7f05002d;
        public static int ft_notification_transaction_completed=0x7f05001a;
        public static int ft_notification_transaction_failed=0x7f050019;
        /**  financial transaction progress 
         */
        public static int ft_progress_title=0x7f050015;
        public static int ft_started=0x7f050017;
        public static int ft_starting=0x7f050016;
        public static int logs_completed=0x7f050014;
        /**  logs download 
         */
        public static int logs_download=0x7f050026;
        public static int logs_download_finish=0x7f050027;
        /**  download device logs  state 
         */
        public static int logs_progress_title=0x7f050012;
        public static int logs_starting=0x7f050013;
        public static int no=0x7f050004;
        public static int none_found=0x7f05000c;
        public static int none_paired=0x7f05000b;
        public static int not_connected_to_ped=0x7f050029;
        public static int operation_in_progress=0x7f05002c;
        public static int progress_scanning=0x7f050021;
        public static int scanning=0x7f05000d;
        public static int select_device=0x7f05000e;
        public static int status_special_4097=0x7f05002e;
        public static int status_special_4098=0x7f05002f;
        public static int status_special_4099=0x7f050030;
        public static int sv_negative_button_label=0x7f050039;
        /**  Signature verification 
         */
        public static int sv_notification_text=0x7f050037;
        public static int sv_positive_button_label=0x7f050038;
        public static int sv_signature_verified=0x7f05003a;
        public static int th_message=0x7f050034;
        public static int th_negative_button_label=0x7f050036;
        public static int th_positive_button_label=0x7f050035;
        /**  Timeout handler 
         */
        public static int th_waiting_timeout_handling=0x7f050033;
        public static int title_other_devices=0x7f050009;
        /**  device list 
         */
        public static int title_paired_devices=0x7f050008;
        public static int try_again=0x7f050006;
        public static int turning_off_bt=0x7f05001f;
        public static int turning_on_bt=0x7f05001e;
        public static int xml_cmd_completed=0x7f050011;
        /**  xml command state 
         */
        public static int xml_cmd_progress_title=0x7f05000f;
        public static int xml_cmd_starting=0x7f050010;
        public static int yes=0x7f050003;
    }
}
